###########
# Backend #
###########

FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=development

COPY package.json tsconfig.json ./
RUN npm install

# Source will be bind-mounted in development; copy once for initial build
COPY src ./src

EXPOSE 3847

CMD ["npm", "run", "dev"]

